### ISSUE TITLE
any larger model test?

### ISSUE THREAD

**Issue by ildoonet** [google/maxtext#15]
1. Have you conducted efficiency test on more then 100B model?

2. If so, Can I get a sample configuration?

**Comment by rwitten** [comment]
Hi! We didn't formalize any workloads but we experimented up to 120B. Feel free to email me (rwitten@google.com) if you're interested in learning more. The efficiency scales favorably -- MFU's tend to improve with larger models.

What is your hardware configuration (i.e. v3-X, v4-X)? I'm happy to help you find a high performance configuration.
