### ISSUE TITLE
Jobs in kubernetes exceeds the limit of 40 characters

### ISSUE THREAD

**Issue by williampispico** [google/maxtext#214]
I have been trying to delete a job but XPK has a limitation of job name should have less than 40 characters.
In my case, the GKE job name had 44 characters. In order to workaround the problem I bumped the number to 45 and I was able to delete the job with python3 xpk/xpk.py workload delete.

I don't know if the job name limitation has changed recently. but I wanted to give a heads-up about this issue.

https://github.com/google/maxtext/blob/4688665aee6c819868aa054dcd52371c8cb1196a/xpk/xpk.py#L1418

**Comment by Obliviour** [comment]
Hi William! Delighted to hear your usage of XPK.

Quick question: was the GKE job you created with XPK or by GKE commands directly?

Thanks,
Victor

**Comment by rwitten** [comment]
Backstory is that you shouldn't be able to create a job you can't delete with XPK. But if you created the job separately it would make sense this would be possible.

**Comment by williampispico** [comment]
Hey @Obliviour / @rwitten thanks for the reply. 
We are focusing only on XPK to create jobs and new slices in the cluster. Based on what researchers mentioned all jobs are being started via XKP.

**Comment by rwitten** [comment]
We literally don't know how this is possible -- it shouldn't be (but the behavior of XPK changed recently so maybe they were using an old client)! If you ever get a repro let us know.
