### ISSUE TITLE
Do the Attentions / MLPs run in parallel?

### ISSUE THREAD

**Issue by tensorpro** [google/maxtext#218]
The attention implementation [here](https://github.com/google/maxtext/blob/main/MaxText/layers.py#L1081-L1106) looks like like it could be run as parallel attention.

But I was curious whether this implementation will result in them running in parallel?

**Comment by rwitten** [comment]
Yes this is parallel attention. PaLM Section 2 (https://arxiv.org/pdf/2204.02311.pdf).

The fact that they can be overlapped tends to improve performance.
