### ISSUE TITLE
XlaRuntimeError when training with bfloat16 activations on TPU v3-8

### ISSUE THREAD

**Issue by rbflx** [google/maxtext#264]
Hello,

I tried testing MaxText on a TPU v3-8 (using the base.yml config with "dataset_type: synthetic") but am encountering the following error when running train.py:

```python
Traceback (most recent call last):
  File "/home/user/maxtext/MaxText/train.py", line 335, in <module>
    app.run(main)
  File "/home/user/jax_env/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/user/jax_env/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/user/maxtext/MaxText/train.py", line 331, in main
    train_loop(config)
  File "/home/user/maxtext/MaxText/train.py", line 282, in train_loop
    state, metrics, nextrng = p_train_step(
jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: Failed to compile a Mosaic module: 'tpu.matmul' op Unsupported input data type in matrix multiplication. (extra diagnostics trimmed...)
```

The issue seems to lie with the bfloat16 config option for activations (dtype: "bfloat16") since it works when using 'dtype: "float32" (and necessarily scaling the parameter count way down).
Interestingly, trying this small model with bfloat16 results in a slightly different error:

 ```python
# same traceback as before except for last line:
jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: Failed to compile a Mosaic module: failed to legalize operation 'tpu.mask_cast'
```

For reference, this was tested in a fresh Python 3.10 virtualenv.

**Comment by rbflx** [comment]
Update: This seems to be related to flash attention. When using "enable_flash_attention: False", it works with the following performance:

```python
completed step: 26, seconds: 5.180, TFLOP/s/device: 34.863, loss: 0.151
completed step: 27, seconds: 5.179, TFLOP/s/device: 34.869, loss: 0.142
completed step: 28, seconds: 5.178, TFLOP/s/device: 34.876, loss: 0.130
completed step: 29, seconds: 5.181, TFLOP/s/device: 34.862, loss: 0.120
```

which is comparable to the performance reported in this issue: https://github.com/google/maxtext/issues/8 (somewhat lower - maybe due to the lack of flash attention).

I'm still curious, however, whether there is a way to avoid the initial issues when using flash attention?

**Comment by rbflx** [comment]
Closing this as it seems to be a JAX-related issue: https://github.com/google/jax/issues/18595

**Comment by rwitten** [comment]
At the time of ticket #8, our configurations were materially different, I expect that is the main difference on perf. (We definitely didn't have flash attention support!)

We don't test MaxText too much on v3 and I believe landing flash attention is realistically going to be challenging on the v3 platform.
