### ISSUE TITLE
Long sequences are dropped rather than trimmed

### ISSUE THREAD

**Issue by reinerp** [google/maxtext#274]
From reading the dataset code, it looks like long sequences are dropped (https://github.com/google/maxtext/blob/bab4ee78fdeb7a87e0ad01d3f9fa822229ddea07/MaxText/input_pipeline.py#L105) before they get a chance to be trimmed (https://github.com/google/maxtext/blob/bab4ee78fdeb7a87e0ad01d3f9fa822229ddea07/MaxText/sequence_packing.py#L81). This seems probably undesirable to me: some of the best documents in the corpus are likely in long sequences.

For comparison, seqio seems to trim but not discard long sequences (https://github.com/google/seqio/blob/515d917bf58da4103a2bbf39c3716213c36aff03/seqio/feature_converters.py#L535) and tensor2tensor seems to chop long sequences into multiple training examples (https://github.com/tensorflow/tensor2tensor/blob/bafdc1b67730430d38d6ab802cbd51f9d053ba2e/tensor2tensor/data_generators/generator_utils.py#L612-L614). The tensor2tensor approach seems best, since we don't waste tokens from some of the (hypothesized) best documents in our corpus.

**Comment by rwitten** [comment]
Thanks for the tip Reiner and always happy to connect if you're using MaxText.

@aireenmei I'll leave this assigned to you because we should address it as part of the data input pipeline refactoring you're doing.

**Comment by rwitten** [comment]
Solved in 352
