### ISSUE TITLE
Can AQT be used to calculate qk score?

### ISSUE THREAD

**Issue by Lisennlp** [google/maxtext#478]
Thanks to the author for this contribution, I see that the code only performs aqt operations on calculations involving parameters. Can aqt be used for the calculation of qk attention score or score * V in the Attention calculation?

I train model on jax==0.4.23 and tpu v5p-8

**Comment by rwitten** [comment]
Not recommended. SplashAttention is faster and AQT won't help in attention becuase we're so close to being vector processing unit (VPU) bound.
