### ISSUE TITLE
setup.sh runs `rm ~/jax`

### ISSUE THREAD

**Issue by mattjj** [google/maxtext#480]
https://github.com/google/maxtext/blob/490f75b98644529eefbde1d8018263d81787e144/setup.sh#L91-L94

```python
# Delete jax folder if it exists
if [[ -d $HOME/jax ]]; then
    rm -rf $HOME/jax
fi
```

This seems dangerous!

Maybe it's intended only to run on worker nodes rather than users' development machines, and maybe it's only meant to be clearing up its own cached directories. But even if that's the case it seems like we might be able to improve it, like by installing in less common directory names (maybe all under a `~/maxtext_cache`, so `~/maxtext_cache/jax` rather than `~/jax`?).

**Comment by rwitten** [comment]
@mattjj @tonyjohnchen  Sorry to hear about the data loss. We'll get this fixed.

**Comment by rwitten** [comment]
@mattjj are you actually using this feature? If not we'd just go with:
https://github.com/google/maxtext/pull/484

**Comment by dougalm** [comment]
It was actually me who ran into the problem (Matt filed the bug because I was too lazy to do it). Can confirm that I wasn't intending to use the `head` feature. I just don't want install scripts deleting chunks of my home directory!

**Comment by mattjj** [comment]
No data was harmed as far as I know. #484 looks good!

**Comment by tonyjohnchen** [comment]
https://github.com/google/maxtext/pull/484 was merged and close this issue.
