### ISSUE TITLE
Pin `aqtp==0.5.0` when building on top of base image with python<3.11

### ISSUE THREAD

**Issue by chajath** [google/maxtext#500]
aqtp>=0.6.0 has various python 3.11 typing constructs that are not compatible with 3.10 base images. Since there are docker build files that use 3.10, we probably should pint aqtp to the latest known 3.10 compatible version.

**Comment by gobbleturk** [comment]
Apologies for the breakage, I think this was recognized and a fix was issued with a new aqtp release 0.6.1 (just hours ago). Let us know if you have issues even on 0.6.1. We definitely want to support python 3.10

**Comment by chajath** [comment]
Confirmed 0.6.1 works
