### ISSUE TITLE
Convert Gemma weights with scan layers

### ISSUE THREAD

**Issue by borisdayma** [google/maxtext#528]
Hi,

It would be nice to be able to convert the Gemma checkpoints to support scan layers.
This will allow faster compilation for training & inference.

Thanks

**Comment by rwitten** [comment]
Gemma comes out scanned by default right? And when it is time to unscan use this one:
https://github.com/google/maxtext/blob/main/MaxText/generate_param_only_checkpoint.py

**Comment by borisdayma** [comment]
Oh thanks!
I got confused initially by this line with `scan_layers=false`: https://github.com/google/maxtext/blob/02d83aa564df985512b2e3b110c3deae5b89c2c9/MaxText/inference_scratch/gemma_7b.sh#L8

After inspecting the weights I can see they’re scanned.
Just curious why it’s scanned over `param_scan_axis: 1` instead of just `0`.
