### ISSUE TITLE
Gemma instructions were deleted in commit

### ISSUE THREAD

**Issue by emergenz** [google/maxtext#579]
The Gemma instructions at `https://github.com/google/maxtext/blob/main/getting_started/Run_Gemma.md` were deleted in commit 04fa373. As such, the link to that file in https://github.com/google/maxtext#getting-started gives a 404.

**Comment by emergenz** [comment]
Similarly, `https://github.com/google/maxtext/blob/main/end_to_end/gemma/test_convert_chkpt.sh` doesn't exist any more, hence the pointer to that file in https://github.com/google/maxtext/blob/main/end_to_end/gemma/Run_Gemma.md#gemma should be removed.

**Comment by rwitten** [comment]
Wow I was just debugging this, thank you for being a step ahead.
