### ISSUE TITLE
Clarification: how does Llama-2-7b fit on a v4-8 when using Adam?

### ISSUE THREAD

**Issue by rodrigo-f-nogueira** [google/maxtext#606]
My understanding is that we need 20 bytes per parameter when using the Adam optimizer with weights and accumulators stored in float32: https://github.com/google/maxtext/blob/f52e6f7b49277688f68a58284d1ff7873122ca41/MaxText/configs/base.yml#L72.
 
Llama-2-7b thus need (at least) 6.7B * 20 = 134 GB of memory. However, we were able train it on v4-8, which has only 128GB. 

Am I missing something?
Thanks!

**Comment by rwitten** [comment]
12 bytes per parameter, right? Should just barely fit.

12 * 6.7B = 80.4GB, all is well

**Comment by rwitten** [comment]
Closing

**Comment by rodrigo-f-nogueira** [comment]
Great, thank you for the answer but, for instance, in NLG 530B paper (https://arxiv.org/pdf/2201.11990), they mention we need 20 bytes per parameter:

<img width="990" alt="Screen Shot 2024-04-24 at 9 14 08 AM" src="https://github.com/google/maxtext/assets/121117945/8dcedb22-c528-42e1-ae1e-9d4ca8403f94">


Perhaps in the MaxText implementation we don't need the extra copy of weights and activations in fp16 (2+2 bytes) because we are casting 32->16bit everytime we do matmul?
