### ISSUE TITLE
Consolidate inference related logic under jetstream-maxtext

### ISSUE THREAD

**Issue by ahg-g** [google/maxtext#612]
A couple of things:

1) Use `jetengine-maxtext` as the main name for the MaxText engine implementation of JetEngine  (similar to jetengine-pytorch)
2) Create a directory named jetengine-maxtext and move all jetstream serving related logic to that directory, and represents the entry point for serving
3) Update the main readme file to link to this directory

**Comment by rwitten** [comment]
Closing this for internal ticket. Thanks @ahg-g
