### ISSUE TITLE
pip install maxtext

### ISSUE THREAD

**Issue by mblondel** [google/maxtext#64]
Hello! It would be great if we can just pip install maxtext. This would allow other packages to easily depend on it. In case this is useful, we've been using the following github workflow happily for pushing to pypi automatically upon each release:
https://github.com/google/jaxopt/blob/main/.github/workflows/publish_to_pypi.yml

**Comment by priyanka-ganesha** [comment]
Hi, thanks for the suggestion!
We'd love to look into making this possible. Could you elaborate on your use case a bit more and how you plan on using maxtext after pip installing, so we have some more context?

**Comment by rwitten** [comment]
Closing out.
