### ISSUE TITLE
Eval on C4?

### ISSUE THREAD

**Issue by tjingrant** [google/maxtext#711]
Hello, thanks for developing this great project!

I wonder why by default MaxText does not return eval iterator, i.e., why is the second parameter None? This is at least the case for when dataset type is tfds. I wonder what should I do to enable eval during training?

https://github.com/google/maxtext/blob/180a7807598449a7511f37e822253f6679e02009/MaxText/input_pipeline/input_pipeline_interface.py#L74

Would it be okay if I simply return the eval_iter returned by preprocess_dataset as in below? From my experiments this modification does not work out of the box; but wonder if this is the right direction.

https://github.com/google/maxtext/blob/180a7807598449a7511f37e822253f6679e02009/MaxText/input_pipeline/input_pipeline_interface.py#L66

**Comment by aireenmei** [comment]
Eval is supported now: https://github.com/google/maxtext/pull/738
