### ISSUE TITLE
aqtp release 0.8.0 breaking dependencies

### ISSUE THREAD

**Issue by bernardhan33** [google/maxtext#849]
https://pypi.org/project/aqtp/#history releases 0.8.0 an hour ago and is breaking dependencies. [Unit Test](https://github.com/google/maxtext/actions/runs/10586546094/job/29335988745#step:5:594) is failing with the same error too. Current workaround is pinning aqtp to 0.7.5.

**Comment by gobbleturk** [comment]
Thank you for finding this even faster than our unit tests! AQT team released 0.8.1 to fix
